### ISSUE TITLE
Adição de pacotes Padrão

### ISSUE THREAD

**Issue by Clifte** [omadson/modelo-dissertacao-ppgcc#4]
Os seguintes pacotes são básicos para qualquer trabalho na área, seria interessante inseri-los.
\usepackage{algorithmic,algorithm}
\usepackage{amsmath}
\usepackage{amsfonts} 

Como consequência do pacote algoritimic os comandos while,for, if, .... deveriam ser traduzidos.

**Comment by omadson** [comment]
@Clifte, gostei dessa sugestão. Vou adicionar os pacotes `amsmath` e `amsfonts`. Para criação de pseudocódigos adicionarei outro pacote. No próxima _release_ você poderá ver.
