### ISSUE TITLE
Simplificação do arquivo dissertacao.tex

### ISSUE THREAD

**Issue by Clifte** [omadson/modelo-dissertacao-ppgcc#5]
Simplificação do arquivo dissertacao.tex
Nele poderia ser retirado todas as definições padrões e colocadas em outros arquivos.
Isso permitiria que o usuário se concentrasse em apenas inserir pacotes customizados, indicar a ordem de seus capítulos e adicionar seus .bibs.

**Comment by omadson** [comment]
@Clifte, gostei da sua sugestão, porém acho que o projeto ficará muito fragmentado. Desculpa, mas não poderei atender.
