### ISSUE TITLE
Commando para adicionar "comentários" inline

### ISSUE THREAD

**Issue by Clifte** [omadson/modelo-dissertacao-ppgcc#6]
parametro 1: Distância do comentario
2 conteúdo do código
3 conteúdo do comentário

**\newcommand{\STATECOMMENT}[3]{\STATE \parbox{ #1 }{ #2 \hfill}#3}**

**Comment by omadson** [comment]
Eu já estou resolvendo isso. Assim que resolver dou um commit :+1:

**Comment by omadson** [comment]
@Clifte, já resolvi o que você havia requisitado, faça um pull e veja as modificações.

Agora você pode inserir os comentários apenas usando `\Comment{Seu comentário}`
